sudo: false
language: node_js

node_js:
  - "node"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

install:
  - npm install

script:
  - npm run lint
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
